### ISSUE TITLE
Throws unneeded errors

### ISSUE THREAD

**Issue by AbdulHpy** [FlightSystemDevelopment/AppSys21#4]
The code could be modified a bit to not throw any unneeded errors in the
errors channel, instead it could throw errors that actually important so it can be something like
this.

```py
import discord
from discord.ext import commands


...


@Cog.listener()
async def on_command_error(self, ctx, error):
    # Add your own code
    if isinstance(error, commands.CommandNotFound):
            await ctx.send("That command does not exist")
    else:
           channel = self....
           await channel.send(error)

```

To prevent it from blocking errors.

**Comment by AbdulHpy** [comment]
@AFKPilot 

The errors are mostly full of stuff like "User didn't specify member" which I consider useless so I think it blocks needed errors..

**Comment by AFKPilot** [comment]
What errors do you consider needed then? 
@AbdulHpy

**Comment by mossyegghead01** [comment]
Yiu know i already mqje the command handler right @AbdulHpy

**Comment by mossyegghead01** [comment]
Wait realized something, you mean like we dont need to throw the error to #errors except its an unexpected error?

**Comment by AbdulHpy** [comment]
> Wait realized something, you mean like we dont need to throw the error to #errors except its an unexpected error?

Yes that's what I'm talking about.

**Comment by mossyegghead01** [comment]
> > Wait realized something, you mean like we dont need to throw the error to #errors except its an unexpected error?
> 
> Yes that's what I'm talking about.

Understandable, have a great day.

**Comment by AbdulHpy** [comment]
> What errors do you consider needed then?
> @AbdulHpy

Important errors such as python errors

**Comment by AbdulHpy** [comment]
So should I close?

**Comment by AFKPilot** [comment]
No not until the issue is resolved

**Comment by mossyegghead01** [comment]
On it then
